---
# Source: harbor/templates/ingress/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "kccr-harbor-ingress"
  labels:
    heritage: Helm
    release: kccr
    chart: harbor
    app: "harbor"
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: wild-certificate-bd-mir-1-secret
    hosts:
    - kccr.bd-mir-1.klovercloud.io
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kccr-harbor-portal
          servicePort: 80
      - path: /api/
        backend:
          serviceName: kccr-harbor-core
          servicePort: 80
      - path: /service/
        backend:
          serviceName: kccr-harbor-core
          servicePort: 80
      - path: /v2
        backend:
          serviceName: kccr-harbor-core
          servicePort: 80
      - path: /chartrepo/
        backend:
          serviceName: kccr-harbor-core
          servicePort: 80
      - path: /c/
        backend:
          serviceName: kccr-harbor-core
          servicePort: 80
    host: kccr.bd-mir-1.klovercloud.io
---
# Source: harbor/templates/ingress/ingress.yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "kccr-harbor-ingress-notary"
  labels:
    heritage: Helm
    release: kccr
    chart: harbor
    app: "harbor"
  annotations:
    ingress.kubernetes.io/proxy-body-size: "0"
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - secretName: wild-certificate-bd-mir-1-secret
    hosts:
    - notary-kccr.bd-mir-1.klovercloud.io
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: kccr-harbor-notary-server
          servicePort: 4443
    host: notary-kccr.bd-mir-1.klovercloud.io
