---
# Source: harbor/templates/redis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kccr-harbor-redis
  labels:
    heritage: Helm
    release: kccr
    chart: harbor
    app: "harbor"
spec:
  ports:
    - port: 6379
  selector:
    release: kccr
    app: "harbor"
    component: redis
